version: "3.8"

include:
  - path:
      - docker-compose.kafka.yml
      - docker-compose.db.yml

services:
  kafka-test-app-ui:
    build:
      context: ./kafka-test-app-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      KAFKA_CLIENT_ID: kafka-test-app-ui
      KAFKA_BROKERS: kafka1:19092,kafka2:29092,kafka3:39092
      USER_TEXT_MESSAGES_TOPIC: UI_Messages
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  kafka-test-words-counter:
    build:
      context: ./kafka-test-words-counter
      dockerfile: Dockerfile
    environment:
      KAFKA_BROKERS: kafka1:19092,kafka2:29092,kafka3:39092
      USER_TEXT_MESSAGES_TOPIC: UI_Messages
      KAFKA_GROUP_ID: kafka-test-words-counter
      DATABASE_URL: postgres://foo:bar@postgres:5432/kafka_test_app?sslmode=disable
    depends_on:
      - postgres
      - kafka1
      - kafka2
      - kafka3
    deploy:
      mode: replicated
      replicas: 2
